L("which-key", function(wk)
  wk.register({
    b = {
      name = "+buffers",
      ["*"] = { "Grep String" },
      b = { "Show Buffers" },
      d = { "Delete Current Buffer" },
      D = { "Delete All Buffers" },
      w = { "Wipeout Current Buffer" },
      W = { "Wipeout All Buffers" },
    },
    f = {
      name = "+finder",
      ["*"] = { "Grep String" },
      b = { "Fuzzy Find Current Buffer" },
      e = { "Find Treesitter Symbols" },
      f = { "Find Files" },
      g = { "Find Git Files" },
      m = { "Find Marks" },
      r = { "Find Live Grep" },
      R = { "Find Registers" },
    },
    g = {
      name = "+git",
      b = { "Toggle Current Line Blame" },
      d = { "Preview Hunk" },
      f = { "Diffget take Left" },
      j = { "Diffget take Right" },
      m = { "Messenger" },
      s = { "Neogit" },
      u = { "Reset Hunk" },
      B = { "Toggle Line Blame" },
      D = { "Show Diff View" },
      ["+"] = { "Stage Hunk" },
      ["-"] = { "Undo Stage Hunk" },
    },
    l = {
      name = "+language",
      c = {
        name = "+code",
        a = { "Code Action" },
        i = { "Incoming Calls" },
        o = { "Outgoing Calls" },
      },
      d = { "Jump to Definition" },
      f = { "Format" },
      j = { "Next Diagnostic" },
      k = { "Previous Diagnostic" },
      l = { "Line Diagnostics" },
      r = { "Rename" },
      s = { "Show Signature Help" },
      t = {
        name = "+finder",
        d = { "Show Diagnostics (Current Buffer)" },
        i = { "Implementations" },
        r = { "References" },
        s = { "Document Symbols" },
        D = { "Implementations" },
        S = { "Show Diagnostics" },
      },
      D = { "Jump to Declaration" },
      T = { "Jump to Type Definition" },
    },
    p = { "Swap Previous Parameter" },
    s = {
      name = "+search",
      a = { "Autocmds" },
      c = { "Commands" },
      f = { "Functions" },
      k = { "Keymaps" },
      s = { "All" },
    },
    u = {
      name = "+urlview",
      f = { "File" },
      j = { "Jira" },
      p = { "Packer" },
      u = { "Buffer" },
    },
    w = {
      name = "+windows",
      ["*"] = { "Grep String" },
      q = { "Close Window" },
      t = { "Close Tab" },
      o = { "Close All Other Windows" },
      n = {
        name = "+new",
        x = { "Horizontal" },
        v = { "Vertical" },
      },
      s = {
        name = "+split",
        x = { "Horizontal" },
        v = { "Vertical" },
      },
      f = { "Find Files" },
      g = { "Git Files" },
      r = { "Live Grep" },
    },
    z = { "Focus Time" },
    B = {
      name = "+buffers",
      D = { "Delete All Other Buffers" },
      W = { "Wipe All Other Buffers" },
    },
    D = { "Diagnostic Trouble" },
    F = {
      name = "+finder",
      F = { "Find Files (Hidden + Ignored)" },
    },
    K = { "Show Documentation" },
    P = { "Swap Next Parameter" },
    Y = { "Yank Till End" },
    Z = { "Focus Time++" },
    ["<leader>"] = {
      name = "+finder",
      l = { "Show Location List" },
      m = { "Show Messages In Quickfix" },
      n = { "Show Notifications" },
      q = { "Show Quickfix" },
      H = { "Show Help Tags" },
      K = { "Show Keymaps" },
      M = { "Show Man Pages" },
      N = { "Dismiss Notification" },
      T = { "Resume Last Finder" },
    },
    ["<C-n>"] = { "Toggle Nerdtree" },
    ["<C-s>"] = { "Save File" },
    ["<C-H>"] = { "Move Window Left" },
    ["<C-J>"] = { "Move Window Down" },
    ["<C-K>"] = { "Move Window Up" },
    ["<C-L>"] = { "Move Window Right" },
  }, { prefix = "<leader>" })
end)
