local M = {}

M.apply = function()
  L("lush", function(lush)
    local hsl = lush.hsl
    local xres = table.clone(Colors_or_default())
    xres.diffgreen = "#002800"
    xres.diffred = "#3f0000"
    xres.yellow = "#3f3f00"

    for name, color in pairs(xres) do
      xres[name] = hsl(color)
    end
    xres.none = "NONE"

    ---@diagnostic disable: undefined-global, undefined-field
    local theme = lush(function(injected_functions)
      local sym = injected_functions.sym
      return {
        DiffAdd { fg = xres.None, bg = xres.diffgreen },
        DiffDelete { fg = xres.None, bg = xres.diffred },
        DiffChange { fg = xres.None, bg = DiffAdd.bg.ro(60) },
        DiffText { fg = xres.None, bg = DiffAdd.bg.lighten(2.5) },
        DiagnosticError { fg = DiffDelete.bg.lighten(35) },
        DiagnosticWarn { fg = xres.yellow.lighten(35) },
        DiagnosticWarning { DiagnosticWarn },
        DiagnosticInfo { fg = xres.color15, bg = xres.bg.lighten(15) },
        DiagnosticHint { fg = xres.color7 },
        DiagnosticUnderlineError { fg = DiagnosticError.fg, gui = "underline" },
        DiagnosticUnderlineWarn { fg = DiagnosticWarn.fg, gui = "underline" },
        DiagnosticUnderlineInfo { fg = DiagnosticInfo.fg, gui = "underline" },
        DiagnosticUnderlineHint { fg = DiagnosticHint.fg, gui = "underline" },
        DiagnosticVirtualTextError { DiagnosticError },
        DiagnosticVirtualTextWarn { DiagnosticWarn },
        DiagnosticVirtualTextInfo { DiagnosticInfo },
        DiagnosticVirtualTextHint { DiagnosticHint },
        DiagnosticFloatingError { DiagnosticError },
        DiagnosticFloatingWarn { DiagnosticWarn },
        DiagnosticFloatingInfo { DiagnosticInfo },
        DiagnosticFloatingHint { DiagnosticHint },
        DiagnosticSignError { DiagnosticError },
        DiagnosticSignWarn { DiagnosticWarn },
        DiagnosticSignInfo { DiagnosticInfo },
        DiagnosticSignHint { DiagnosticHint },
        SpecialKey { fg = xres.color13, bg = xres.color0 },
        TermCursor { gui = "reverse" },
        Comment { fg = xres.color4, bg = xres.color0 },
        NonText { fg = Comment.fg.lighten(10), bg = xres.None },
        EndOfBuffer { NonText },
        Directory { fg = xres.color11, bg = xres.bg },
        ErrorMsg { fg = xres.color0, bg = xres.color9 },
        Search { gui = "reverse" },
        MoreMsg { fg = xres.color15, bg = xres.bg },
        ModeMsg { fg = xres.none, bg = xres.none, gui = "bold" },
        LineNr { fg = xres.color7, bg = xres.color0 },
        LineNrAbove { LineNr },
        LineNrBelow { LineNr },
        CursorLineNr { fg = xres.color15, bg = xres.color8.lighten(2.5), gui = "bold" },
        Type { fg = xres.color14, bg = xres.bg, gui = "bold" },
        Question { Type },
        StatusLine { fg = xres.color15, bg = xres.color8, gui = "bold" },
        StatusLineNC { fg = xres.color15, bg = xres.color8 },
        SignColumn { fg = xres.color12, bg = xres.none },
        VertSplit { fg = xres.color0, bg = xres.color8, gui = "reverse" },
        Title { fg = xres.fg.lighten(25), bg = xres.bg },
        WildMenu { fg = xres.color0, bg = xres.color11 },
        Keyword { fg = xres.color13 },
        Pmenu { fg = xres.color15, bg = xres.bg },
        PmenuSel { fg = xres.none, bg = xres.bg.lighten(15) },
        PmenuSbar { fg = xres.fg.lighten(25) },
        PmenuThumb { fg = xres.fg, bg = xres.color15 },
        QuickFixLine { Search },
        Substitute { Search },
        Whitespace { NonText },
        MsgSeparator { StatusLine },
        Label { Type },
        Operator { Type },
        StorageClass { Type },
        Structure { Type },
        NvimNumberPrefix { Type },
        NvimOptionSigil { Type },
        Normal { fg = xres.color15, bg = xres.color0 },
        NormalFloat { fg = Normal.fg, bg = xres.bg.lighten(1.5) },
        NvimSpacing { Normal },
        Delimiter { fg = xres.color15, bg = xres.color8 },
        NvimParenthesis { Delimiter },
        NvimColon { Delimiter },
        NvimComma { Delimiter },
        NvimArrow { Delimiter },
        Constant { fg = xres.color11, bg = xres.bg },
        String { Constant },
        Character { Constant },
        Visual { fg = xres.None, bg = xres.color0.lighten(15) },
        Function { fg = xres.color9.ro(15).lighten(15), bg = xres.bg },
        Special { fg = xres.color9 },
        Tag { Special },
        Debug { Special },
        PreProc { fg = xres.color10 },
        Include { PreProc },
        Define { PreProc },
        Macro { PreProc },
        PreCondit { PreProc },
        Conditional { fg = xres.color11 },
        Repeat { Conditional },
        Statement { fg = xres.color10, gui = "bold" },
        Method {},
        Boolean { Statement },
        FloatTitle { fg = xres.color0, bg = xres.fg, gui = "bold" },
        FloatBorder { fg = FloatTitle.bg, bg = xres.bg.lighten(1.5) },
        SpecialChar { fg = xres.color12, bg = xres.color8 },
        SpecialComment { fg = xres.color11, bg = xres.color8 },
        FoldColumn { fg = xres.color14, bg = xres.bg },
        Folded { FoldColumn },
        WarningMsg { fg = xres.color10 },
        Conceal { fg = xres.color7 },
        SpellBad { fg = xres.color8, bg = xres.color9 },
        SpellCap { bg = xres.color12.da(25), gui = "undercurl" },
        SpellRare { bg = xres.color13.da(55), gui = "undercurl" },
        SpellLocal { bg = xres.color8, gui = "undercurl" },
        CursorColumn {},
        CursorLine { bg = xres.color0 },
        ColorColumn { fg = xres.none, bg = xres.color1 },
        NormalNC {},
        MsgArea {},
        RedrawDebugNormal { gui = "reverse" },
        RedrawDebugClear { bg = xres.color11.ro(180).lighten(70) },
        RedrawDebugComposed { bg = xres.color10.da(50) },
        RedrawDebugRecompose { bg = xres.color9.da(50) },
        Cursor { fg = xres.bg, bg = xres.fg },
        lCursor { fg = xres.bg, bg = xres.fg },
        FloatShadow { fg = xres.fg.lighten(15), bg = xres.bg.lighten(15) },
        FloatShadowThrough { fg = xres.color15, bg = xres.bg },
        Error { DiagnosticError },
        Todo { fg = xres.color14, bg = xres.color8 },
        Number { fg = xres.color12 },
        Float { fg = xres.color12 },
        Identifier { fg = xres.color12 },
        Exception { fg = xres.color10, bg = xres.color0 },
        Typedef { fg = xres.color10, bg = xres.color0, gui = "bold" },
        MatchParen { fg = xres.color12, bg = xres.color8 },
        Underlined { fg = xres.color12, gui = "underline" },
        Ignore { fg = xres.color0.lighten(15) },
        User1 { fg = xres.color15, bg = xres.color6 },
        User2 { fg = xres.color15, bg = xres.color8 },
        SatusLineSeperator { fg = xres.color8, bg = xres.None },
        StatusLineTerm { fg = xres.color0 },
        StatusLineTermNC { fg = xres.color15, bg = xres.color8 },
        YCMWarningSection { fg = xres.color0, bg = xres.color4 },
        debugPC {},
        LspReferenceText { bg = xres.color0.lighten(10) },
        LspReferenceRead { SpecialKey },
        LspReferenceWrite { fg = LspReferenceRead.fg.darken(25), bg = LspReferenceRead.bg },
        LspInfoBorder { FloatBorder },
        LspInfoTitle { FloatTitle },
        LspInfoList { fg = xres.color3, bg = xres.bg },
        LspInfoTip { fg = xres.color10, bg = xres.bg },
        diffOnly { Constant },
        diffIdentical { Constant },
        diffDiffer { Constant },
        diffBDiffer { Constant },
        diffIsA { Constant },
        diffNoEOL { Constant },
        diffCommon { Constant },
        diffRemoved { DiffDelete },
        diffAdded { DiffAdd },
        diffChanged { DiffChange },
        diffSubname { PreProc },
        diffLine { Statement },
        diffFile { Type },
        diffOldFile { fg = DiffDelete.bg.lighten(20) },
        diffNewFile { fg = DiffAdd.bg.lighten(20) },
        diffIndexLine { PreProc },
        diffComment { Comment },
        DiffviewFilePanelCounter { fg = xres.color3, bg = xres.None, gui = "bold" },
        GitSignsDelete { fg = diffOldFile.fg.lighten(30) },
        GitSignsDeleteNr { fg = GitSignsDelete.fg },
        GitSignsAdd { fg = diffNewFile.fg.lighten(15) },
        GitSignsAddNr { fg = GitSignsAdd.fg },
        GitSignsChange { fg = DiffAdd.bg.ro(30).lighten(30) },
        GitSignsChangeNr { fg = GitSignsChange.fg },
        GitSignsCurrentLineBlame { fg = NonText.fg.lighten(10) },
        GitSignsDeleteNr = { GitSignsDeleteNr },
        GitSignsUntrackedNr = { GitSignsAddNr },
        GitSignsTopdeleteNr = { GitSignsDeleteNr },
        GitSignsChangedeleteNr = { GitSignsChangeNr },
        OilGitAdded = { GitSignsAdd },
        OilGitModified = { GitSignsChange },
        OilGitModifiedStaged = { GitSignsStagedChange },
        OilGitModifiedUnstaged = { GitSignsChange },
        OilGitRenamed = { GitSignsChange },
        OilGitDeleted = { GitSignsDelete },
        OilGitCopied = { GitSignsChange },
        OilGitConflict = { DiagnosticSignError },
        OilGitUntracked = { GitSignsUntracked },
        OilGitIgnored = { GitSignsCurrentLineBlame },
        NvimString { String },
      }
    end)

    lush(theme)
  end)
end

return M
